### PR TITLE
Update of NEWS and Description due to changes in `get*Tags` function

### PR DESCRIPTION
**Pull request by wchodor**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
You will need to resolve this conlift, since I was working to repair tests and changed few things:
https://github.com/pbiecek/archivist/commit/42914ca734ba43e8dac7b4b0f9ee87fdb85efa64

**Comment by MarcinKosinski** [comment]
The NEWS.md is a litte mesy right now.

- Can you move BUGS:xiii to the NEW_FEATURES:iii?
- BUGS:x -> user doesn't see `testthat` directory. Can you just write `new tests for` an mentioned functions in sublist? and move this from BUGS to NEW_FEATURES?
- NEW_FEATURES:iv - it doesn't mean anything for me - can you extend this sentence or remove it completly?

Could you pleas be so kind and add this information 

`tempdir is existing directory in which R works so calling deleteRepo( exampleRepoDir, deleteRoot=TRUE) removed important R files.` to the `deleteRepo` manual page in `NOTE` section to warn an user to not perform such an operation? You can also give a link to this stackoverflow queastion:

http://stackoverflow.com/questions/22325820/unlink-function-causing-an-error-for-consequent-and-plot-functions

**Comment by wchodor** [comment]
OK, I executed all your requests. Please remember to change `DESCRIPTION` file while you will be updating `NEWS.md` about `url.exists()`

**Comment by MarcinKosinski** [comment]
> OK, I executed all your requests. Please remember to change DESCRIPTION file while you will be updating NEWS.md about url.exists() 

I will not, because this probably isn't the information that user would like to read/ would care about/ would understand the benefit of this change.

**Comment by MarcinKosinski** [comment]
I think you missed this request:



> Could you pleas be so kind and add this information
>
> `tempdir is existing directory in which R works so calling deleteRepo( exampleRepoDir,
deleteRoot=TRUE) removed important R files.`
>
> to the deleteRepo manual page in NOTE section to warn an user to not perform such an operation? You can also give a link to this stackoverflow queastion http://stackoverflow.com/questions/22325820/unlink-function-causing-an-error-for-consequent-and-plot-functions

Moreover what do you think about shortening examples in `deleteRepo`. So far we are having very long examples in there. Maybe we just should:

- copyLocalRepo from graphGallery of the archivist package to some local directory
- then proceed showLocalRepo and summaryLocalRepo on that copied repository
- and then deleteRepo on this repository and that's all?

**Comment by wchodor** [comment]
I didn't. I made a request two minutes ago.

**Comment by wchodor** [comment]
I made those two examples in `deleteRepo` to differ using `deleteRoot` argument. As we know it caused some problems. I wouldn't change this scheme.
If you're talking about length of objects preparation, then I agree it may be too long for this function. But we make this objects preparation in almost every function.

**Pull request merged**
