### PR TITLE
Change of DESCRIPTION and NEWS

### PR DESCRIPTION
**Pull request by wchodor**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
What's the difference between:

>
> Artifacts' data files are now removed from gallery folder when many = TRUE
>
>Artifact's (Artifacts') data files are now removed from gallery folder when many = FALSE

and can you elaborate the `wrong md5hash`? Do you mean that the `md5hash` does not exist in the `Repository`?

**Comment by wchodor** [comment]
1. The difference is in many parameter.
2. This is exactly what I was to say: wrong `md5hash` is the one that does not exist in the `Repository`

**Comment by MarcinKosinski** [comment]
1. So maybe let's write: 

> Artifacts' data files are now removed from gallery folder when many is `TRUE` or `FALSE`

2. I will extend the NEWS.md with that information

**Comment by wchodor** [comment]
OK, it's a good idea.

**Pull request merged**
