### PR TITLE
Tests, removed dependencies. Ver 1.7. 

### PR DESCRIPTION
**Pull request by MarcinKosinski**
shinySearch is an extra function that requires to have shiny installed.

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
Check results
````{Ruby}
==> roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))

Failed with error:  'invalid package name'
Writing Repository.Rd
Writing Tags.Rd
Writing addTagsRepo.Rd
Writing ahistory.Rd
Writing archivist-package.Rd
Writing archivistOptions.Rd
Writing aread.Rd
Writing asearch.Rd
Writing cache.Rd
Writing copyToRepo.Rd
Writing createEmptyRepo.Rd
Writing deleteRepo.Rd
Writing getTags.Rd
Writing loadFromRepo.Rd
Writing magrittr.Rd
Writing md5hash.Rd
Writing rmFromRepo.Rd
Writing saveSetToRepo.Rd
Writing saveToRepo.Rd
Writing searchInRepo.Rd
Writing setRepo.Rd
Writing shinySearchInRepo.Rd
Writing showRepo.Rd
Writing summaryRepo.Rd
Writing zipRepo.Rd
Writing NAMESPACE
Warning message:
package 'RSQLite' was built under R version 3.2.2 
Documentation completed

==> Rcmd.exe build archivist

* checking for file 'archivist/DESCRIPTION' ... OK
* preparing 'archivist':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
Removed empty directory 'archivist/tests/testthat/new_repo'
Removed empty directory 'archivist/tests/testthat/tmp_archivist'
* building 'archivist_1.7.tar.gz'

==> Rcmd.exe check archivist_1.7.tar.gz

* using log directory 'D:/R projects/archivist.Rcheck'
* using R version 3.2.1 (2015-06-18)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'archivist/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'archivist' version '1.7'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'archivist' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R' OK
* checking PDF version of manual ...
 OK
* DONE
Status: OK


R CMD check succeeded
````

**Comment by MarcinKosinski** [comment]
How's that possible that locally all tests passes but on travis they do not?

**Comment by pbiecek** [comment]
There is a message 'stop(gettextf("unable to find required package %s", sQuote(package)), domain = NA)'

So maybe some packages are not installed?

**Comment by MarcinKosinski** [comment]
Oh Yes, probably there is a test with qplot function. And we don't import that package. I'll change this test 

Marcin Kosinski

Dnia 1 wrz 2015 o godz. 21:40 pbiecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
Probably this won't work. I don't understand why this does not pass on travis. Maybe travis requires that testthat package should be in `Imports` but this makes no sense for package development

**Comment by MarcinKosinski** [comment]
Installation passes perfectly
````{Ruby}
> devtools::install_github("MarcinKosinski/archivist")
Downloading github repo MarcinKosinski/archivist@master
Installing archivist
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Kamil/AppData/Local/Temp/Rtmpi85ko8/devtools1f04344c74b/MarcinKosinski-archivist-0d88d7b"  \
  --library="C:/Users/Kamil/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'archivist' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (archivist)
> 
````

**Comment by MarcinKosinski** [comment]
Ok build have passed with no errors. I had to add ggplot package to Suggests and a line `library(ggplot)` to the `tests/testthat.R` file.

You can Merge pull request now.

**Pull request closed without merging**
