### PR TITLE
Alterations of zip*Repo's function documentation as well as body

### PR DESCRIPTION
**Pull request by wchodor**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
I've seen you had +1000 lines of code yesterday.  Gratz!
https://github.com/pbiecek/archivist/graphs/contributors

**Comment by MarcinKosinski** [comment]
Can this statement from NEWS.md `paste0() function was replaced by file.path() function in appropriate places.` can be placed globally and specified which function have had those change INSTEAD of having it only in `zip*Repo`?

**Comment by MarcinKosinski** [comment]
Is this line `tempRepoTo <- checkDirectory( tempRepoTo )` even necessary since `createEmptyRepo` also uses this function at the beggining?

**Comment by wchodor** [comment]
FIRST question: It is a good idea.
SECOND question: You're right. We may omit this line.

**Comment by wchodor** [comment]
I will reorganize `NEWS.md` and remove that line from function's body

**Comment by MarcinKosinski** [comment]
Can you add a test for `zip*Repo` to `tests` since you fixed this function and are claiming there was a rodeo with github version?We'll then have full trust in changes that were made :)

**Comment by MarcinKosinski** [comment]
I write this not to forget about that:

We could prepare example test such as:

1. Create a repo on github, then use zipGithub and check te size of `.zip` file
1. Create a local repo, then use zipLocal and then unzip and check if the number of files in origin repo is the same as in unzipped repo

**Pull request merged**
