### PR TITLE
Alterations of functions' bodies and new test

### PR DESCRIPTION
**Pull request by wchodor**
Alterations of functions' bodies:
- `downloadDB` in `createEmptyRepo`,
- `zipGithubRepo`.

New test of `zip*Repo` function.

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
Ok we have few problems with tests.
Hmm I think I'll merge this PR (pull-request) and I'll try to fix tests on my own?
@wchodor  is that OK for you?

**Comment by wchodor** [comment]
Which tests do you mean?

**Comment by MarcinKosinski** [comment]
Scroll to the bottom of the page: https://travis-ci.org/pbiecek/archivist/builds/89847071

**Comment by wchodor** [comment]
It would be nice of you to fix this on your own.

**Comment by MarcinKosinski** [comment]
Everything went fine but we didn't add `url.exists` (new function) to package NAMESPACE via `@importFrom ` in `archivist-package.R` - this commit fixed this https://github.com/pbiecek/archivist/commit/42914ca734ba43e8dac7b4b0f9ee87fdb85efa64

**Comment by MarcinKosinski** [comment]
I'll write developers note to sumup all operations that every developer should know when maintaining and testing a package

**Pull request merged**
